const express = require('express');
const router = express.Router();
const nurseController = require('../controllers/nurseController');
router.get('/schedule', nurseController.getSchedule);
router.get('/instructions', nurseController.getInstructions);
router.put('/instruction/:id/complete', nurseController.completeInstruction);
router.get('/patient-requests', nurseController.getPatientRequests);
router.put('/patient-request/:id/handle', nurseController.handlePatientRequest);
router.get('/equipments', nurseController.getEquipments);
router.post('/equipment-request', nurseController.requestEquipment);
module.exports = router;